import ANSI as A

moedas_paises = {
    "AED": "Dirham árabe - Emirados Árabes Unidos",
    "AFN": "Afghani - Afeganistão",
    "ALL": "Lek albanês - Albânia",
    "AMD": "Dram armênio - Armênia",
    "ANG": "Florin das Antilhas - Sint Maarten, Curaçao",
    "AOA": "Kwanza angolano - Angola",
    "ARS": "Peso argentino - Argentina",
    "AUD": "Dólar australiano - Austrália, Ilha de Natal, Ilhas Cocos, Nauru, Ilha Norfolk, Ouvido e Ilhas McDonald",
    "AWG": "Florim arubano - Aruba",
    "AZN": "Manat azeri - Azerbaijão",
    "BAM": "Marca conversível - Bósnia e Herzegovina",
    "BBD": "Dólar de Barbados - Barbados",
    "BDT": "Taka de Bangladesh - Bangladesh",
    "BGN": "Lev búlgaro - Bulgária",
    "BHD": "Dinar bahraini - Bahrein",
    "BIF": "Franco burundiano - Burundi",
    "BMD": "Dólar Bermudiano - Bermudas",
    "BND": "Dólar Brunei - Brunei",
    "BOB": "Boliviano - Bolívia",
    "BRL": "Real Brasileiro - Brasil",
    "BSD": "Dólar das Bahamas - Bahamas",
    "BTN": "Ngultrum butanês - Butão",
    "BWP": "Pula do Botsuana - Botsuana",
    "BYN": "Rublo bielorrusso - Belarus",
    "BZD": "Dólar de Belize - Belize",
    "CAD": "Dólar canadense - Canadá",
    "CDF": "Franco congolês - República Democrática do Congo",
    "CHF": "Franco suíço - Liechtenstein, Suíça",
    "CLP": "Peso chileno - Chile",
    "CNY": "Yuán Renminbi - China",
    "COP": "Peso colombiano - Colômbia",
    "CRC": "Colón riquenho - Costa Rica",
    "CUP": "Peso cubano - Cuba",
    "CVE": "Escudo cabo-verdiano - Cabo Verde",
    "CZK": "Coroa tcheca - República Tcheca",
    "DJF": "Franco da Djibouti - Djibouti",
    "DKK": "Coroa dinamarquesa - Groenlândia, Dinamarca",
    "DOP": "Peso dominicano - República Dominicana",
    "DZD": "Dinar argelino - Argélia",
    "EGP": "Libra egípcia - Egito",
    "ERN": "Nakfa da Eritreia - Eritreia",
    "ETB": "Birr etíope - Etiópia",
    "EUR": "Euro - União Europeia e outros",
    "FJD": "Dólar de Fiji - Fiji",
    "FKP": "Libra falconiana - Ilhas Malvinas",
    "FOK": "Coroa das Ilhas Faroe - Ilhas Faroe",
    "GBP": "Libra esterlina - Reino Unido e territórios",
    "GEL": "Lari georgiano - Geórgia",
    "GGP": "Libra de Guernsey - Guernsey",
    "GHS": "Cedi ganense - Gana",
    "GIP": "Libra de Gibraltar - Gibraltar",
    "GMD": "Dalasi gambiano - Gâmbia",
    "GNF": "Franco da Guiné - Guiné",
    "GTQ": "Quetzal da Guatemala - Guatemala",
    "GYD": "Dólar guianês - Guiana",
    "HKD": "Dólar de Hong Kong - Hong Kong",
    "HNL": "Lempira hondurenha - Honduras",
    "HTG": "Gourde haitiano - Haiti",
    "HUF": "Forint húngaro - Hungria",
    "IDR": "Rúpia indonésia - Indonésia",
    "ILS": "Shekel israelense - Israel, Palestina",
    "IMP": "Libra da Ilha de Man - Ilha de Man",
    "INR": "Rúpia indiana - Índia",
    "IQD": "Dinar iraquiano - Iraque",
    "IRR": "Rial iraniano - Irã",
    "ISK": "Coroa islandesa - Islândia",
    "JEP": "Libra de Jersey - Jersey",
    "JMD": "Dólar jamaicano - Jamaica",
    "JOD": "Dinar jordaniano - Jordânia",
    "JPY": "Iene japonês - Japão",
    "KES": "Xelim queniano - Quênia",
    "KGS": "Som quirguiz - Quirguizistão",
    "KHR": "Riel cambodjano - Camboja",
    "KID": "Dólar kiribatiano - Kiribati",
    "KMF": "Franco comoriano - Comores",
    "KPW": "Won norte-coreano - Coréia do Norte",
    "KRW": "Ganhou sul-coreano - Coréia do Sul",
    "KWD": "Dinar kuwaitiano - Kuwait",
    "KYD": "Dólar caimão - Ilhas Cayman",
    "KZT": "Tenge cazaque - Cazaquistão",
    "LAK": "Kip laociano - Laos",
    "LBP": "Libra libanesa - Líbano",
    "LKR": "Rúpia do Sri Lanka - Sri Lanka",
    "LRD": "Dólar liberiano - Libéria",
    "LSL": "Loti Lesotho - Lesotho",
    "LYD": "Dinar líbio - Líbia",
    "MAD": "Dirham marroquino - Saara Ocidental, Marrocos",
    "MDL": "Leu moldavo - Moldávia",
    "MGA": "Ariary de Madagascar - Madagascar",
    "MKD": "Denar macedônio - Macedônia do Norte",
    "MMK": "Kyat birmanês - Mianmar",
    "MNT": "Tögrög da Mongólia - Mongólia",
    "MOP": "Pataca de Macau - Macau",
    "MRU": "Ouguiya mauritano - Mauritânia",
    "MUR": "Rúpia das Ilhas Maurício - Maurício",
    "MVR": "Rúpia maldívia - Maldivas",
    "MWK": "Kwacha do Malawi - Malauí",
    "MXN": "Peso mexicano - México",
    "MYR": "Ringgit da Malásia - Malásia",
    "MZN": "Metical moçambicano - Moçambique",
    "NAD": "Dólar namibiano - Namíbia",
    "NGN": "Naira nigeriana - Nigéria",
    "NIO": "Córdoba Oro nicaraguense - Nicarágua",
    "NOK": "Coroa norueguesa - Noruega e territórios",
    "NPR": "Rúpia nepalesa - Nepal",
    "NZD": "Dólar neozelandês - Nova Zelândia e territórios",
    "OMR": "Rial de Omã - Omã",
    "PAB": "Balboa panamenho - Panamá",
    "PEN": "Sol peruano - Peru",
    "PGK": "Kina da Papua Nova Guiné - Papua Nova Guiné",
    "PHP": "Peso filipino - Filipinas",
    "PKR": "Rúpia paquistanesa - Paquistão",
    "PLN": "Zloty polonês - Polônia",
    "PYG": "Guaraní paraguaio - Paraguai",
    "QAR": "Rial do Qatar - Qatar",
    "RON": "Leu romeno - Romênia",
    "RSD": "Dinar sérvio - Sérvia",
    "RUB": "Rublo russo - Rússia",
    "RWF": "Franco ruandês - Ruanda",
    "SAR": "Rial saudita - Arábia Saudita",
    "SBD": "Dólar das Ilhas Salomão - Ilhas Salomão",
    "SCR": "Rúpia das Seychelles - Seychelles",
    "SDG": "Libra Sudanesa - Sudão",
    "SEK": "Coroa sueca - Suécia",
    "SGD": "Dólar de Cingapura - Cingapura",
    "SHP": "Libra de Santa Helena - Santa Helena e territórios",
    "SLE": "Leone da Serra Leoa - Serra Leoa",
    "SOS": "Xelim somali - Somália",
    "SRD": "Dólar surinamês - Suriname",
    "SSP": "Libra do Sudão do Sul - Sudão do Sul",
    "STD": "Dobra são-tomense - São Tomé e Príncipe",
    "SYP": "Libra de Síria - Síria",
    "SZL": "Swazi lilangeni - Eswatini",
    "THB": "Baht tailandês - Tailândia",
    "TJS": "Somoni tadjique - Tajiquistão",
    "TMT": "Manat turcomeno - Turcomenistão",
    "TND": "Dinar tunisino - Tunísia",
    "TOP": "Pa'anga tonganês - Tonga",
    "TRY": "Lira turca - Turquia",
    "TTD": "Dólar de Trinidad e Tobago - Trinidad e Tobago",
    "TVD": "Dólar de Tuvalu - Tuvalu",
    "TWD": "Novo dólar taiwanês - Taiwan",
    "TZS": "Xelim tanzaniano - Tanzânia",
    "UAH": "Grívnia ucraniana - Ucrânia",
    "UGX": "Xelim ugandês - Uganda",
    "USD": "Dólar americano - Estados Unidos e territórios",
    "UYU": "Peso uruguaio - Uruguai",
    "UZS": "So'm uzbeque - Uzbequistão",
    "VED": "Bolívar digital - Venezuela",
    "VND": "Dong vietnamita - Vietnã",
    "VUV": "Vatu de Vanuatu - Vanuatu",
    "WST": "Tala samoano - Samoa",
    "XCD": "Dólar do Caribe Oriental - Caribe Oriental",
    "XPF": "Franco do Pacífico - Polinésia Francesa e outros",
    "YER": "Rial iemenita - Iêmen",
    "ZAR": "Rand sul-africano - África do Sul",
    "ZMW": "Kwacha zambiano - Zâmbia",
    "ZWL": "Dólar zimbabuense - Zimbábue"
}

def listar_moedas():
    print(f"""
          {A.SUBLINHADO}{A.NEGRITO}=== Lista de Moedas e Países ===
          {A.RESET}""")
    for codigo, info in moedas_paises.items():
        print(f"{codigo} - {info}")

listar_moedas()
